name: Blith1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+2
  url_launcher: ^5.2.5
  vs_scrollbar: ^0.1.2
  
  # draggable_scrollbar: ^0.0.4



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"
  
  # flutter_launcher_icons: ^0.9.0

# flutter_icons :
# android : 

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appLogo.png" 
  adaptive_icon_background: "0xff26292e"
  adaptive_icon_foreground: "assets/appLogo.png"      

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Bold.ttf
    - family: ProximaNova
      fonts:
        - asset: fonts/Proxima-Nova-Black.otf
    - family: IntroInline
      fonts:
        - asset: fonts/Intro-Inline.otf
    - family: OstrichSansInline
      fonts:
        - asset: fonts/OstrichSansInline-Regular.otf        
    - family: GlaschuInline
      fonts:
        - asset: fonts/Glaschu-Inline.otf        
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/AAAG.jpg
    - assets/amul.jpg
    - assets/AquaFeelLogo.png
    - assets/appLogo.png 
    # - assets/ATKT_Logo_1.png
    - assets/ATKT_Logo_2.png
    - assets/BangaloreOpenAirLogo.jpeg
    - assets/breakout-logo.jpg
    - assets/BrewHouseLogo.png
    - assets/CanaraBankLogo.png
    - assets/CapitalDentalLogo.PNG
    - assets/DTAGGBlackLogo.png
    - assets/email_logo_green.png
    - assets/facebook_logo_yellow.png
    - assets/Garvi_Logo.jpg
    - assets/Garvi.png
    - assets/GVFL.jpg
    - assets/GIL_Logo.png
    - assets/grand-mercure.jpeg
    - assets/IciciBankLogo.png
    - assets/insta_logo_yellow.png
    - assets/insta_logo_yellow2.png    
    - assets/ITC_Logo.jpg
    - assets/JawedHabibLogo.png
    - assets/JK_Logo.jpg
    - assets/KHS_Logo.png
    - assets/Monster_Logo.jpg
    - assets/OrientalAromatics_Logo.jpg
    - assets/paytm.jpeg
    - assets/play-station.jpeg
    - assets/RagaRockLogo.png
    - assets/RazaFoundationLogo.png
    - assets/Respawn_Logo.png
    - assets/SouledStore_Logo.jpg
    - assets/StatusFashionLogo.PNG
    - assets/tea-post.jpg
    - assets/TheComedyJamsLogo.png
    - assets/TinderName_Logo.png
    # - assets/TinderSign_Logo.png
    - assets/TownScript_Logo.png
    - assets/twitter_logo_yellow.png
    - assets/UnionBank_Logo.png
    - assets/Vivo_Logo.png
    - assets/website_logo_green.png
    - assets/WhiteHeavenEntBlackLogo.jpg
    # - assets/WhiteHeavenEntWhiteLogo.jpg
    - assets/youtube_logo_yellow.png
    # - assets/Zebronics_BnW_Logo.png
    - assets/ZebronicsLogo.jpg
    - assets/sample-bitmoji.png
    - assets/bitmoji/abhiram.png
    - assets/bitmoji/adarsh.png
    - assets/bitmoji/anushka.png
    - assets/bitmoji/ashwani.png
    - assets/bitmoji/dhvani.png
    - assets/bitmoji/eshika.png
    - assets/bitmoji/isha.png
    - assets/bitmoji/ishan.png
    - assets/bitmoji/juhi.png
    - assets/bitmoji/pratham.png
    - assets/bitmoji/rishitha.png
    - assets/bitmoji/rushik.png
    - assets/bitmoji/gautam.png
    - assets/bitmoji/saagar.png
    - assets/bitmoji/paras.png
    - assets/thumbnails/thumbnail_ExaggeratAD.png
    - assets/thumbnails/thumbnail_LenzLaw.jpg
    - assets/thumbnails/thumbnail_Mezkala.png
    - assets/thumbnails/thumbnail_Quizzitch.png
    - assets/thumbnails/thumbnail_Reverb.png
    - assets/thumbnails/thumbnail_Skirmish.png
    - assets/thumbnails/thumbnail_Unkahi.png
    - assets/thumbnails/thumbnail_BlithPD.jpg
    - assets/social/youtube_white.png
    - assets/social/insta_white.png
    - assets/social/website_white.png
    - assets/social/email_white.png
    - assets/social/twitter_white.png
    - assets/social/facebook_white.png
    - assets/gujaratTourism.png
    - assets/ITC.png
    - assets/Score.png
    - assets/sparsh.png
    - assets/Spartan.png
    - assets/yocket.png



    
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages